# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  tools:
    python: "3.6"

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
  system_packages: true
