# Configuration file to run tests on Travis-CI via GitHub notifications
# See http://travis-ci.org/

language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - "pip install -r requirements.txt"
  - "pip install ."

script:
# Run the unit tests for bcftbx
  - "python setup.py test"

